<?php

class dbConfig {

//define user table
    CONST TABLE_USER = 'tbl_user';
    CONST TABLE_USER_ATT_USER_ID = 'userId';
    CONST TABLE_USER_ATT_USER_FIRSTNAME = 'userFirstName';
    CONST TABLE_USER_ATT_USER_LASTNAME = 'userLastName';
    CONST TABLE_USER_ATT_USER_USERNAME = 'userUserName';
    CONST TABLE_USER_ATT_USER_PASSWORD = 'userPassword';
    CONST TABLE_USER_ATT_USER_EMAIL = 'userEmail';
    CONST TABLE_USER_ATT_USER_LAST_LOGIN_TIME = 'userLastLoginTime';
    CONST TABLE_USER_ATT_USER_IS_ACTIVE = 'userIsActive';
    CONST TABLE_USER_ATT_USER_PREVILEDGE = 'userPreviledge';
//define client table
    CONST TABLE_CLIENT = 'tbl_client';
    CONST TABLE_CLIENT_ATT_ID = 'clientId';
    CONST TABLE_CLIENT_ATT_COMPANY = 'clientCompany';
    CONST TABLE_CLIENT_ATT_USER_ID = 'userId';
    CONST TABLE_CLIENT_ATT_FILE_NUMBER = 'clientFileNumber';
    CONST TABLE_CLIENT_ATT_FIRST_NAME = 'clientFirstName';
    CONST TABLE_CLIENT_ATT_LAST_NAME = 'clientLastName';
    CONST TABLE_CLIENT_ATT_ADDRESS = 'clientAddress';
    CONST TABLE_CLIENT_ATT_COUNTRY = 'clientCountry';
    CONST TABLE_CLIENT_ATT_STATE = 'clientState';
    CONST TABLE_CLIENT_ATT_CITY = 'clientCity';
    CONST TABLE_CLIENT_ATT_ZIP = 'clientZip';
    CONST TABLE_CLIENT_ATT_CELL_CONTACT_NUMBER = 'clientCellContactNumber';
    CONST TABLE_CLIENT_ATT_HOME_CONTACT_NUMBER = 'clientHomeContactNumber';
    CONST TABLE_CLIENT_ATT_EMAIL = 'clientEmail';
    CONST TABLE_CLIENT_ATT_COMMENT = 'clientComment';
    CONST TABLE_CLIENT_ATT_ADDED_TIME = 'addedTime';
    CONST TABLE_CLIENT_ATT_IS_DELETE = 'isDelete';
    //define company table
    CONST TABLE_COMPANY = 'tbl_company';
    CONST TABLE_COMPANY_ATT_ID = 'companyId';
    CONST TABLE_COMPANY_ATT_NAME = 'companyName';
    CONST TABLE_COMPANY_ATT_USER_ID = 'userId';
    CONST TABLE_COMPANY_ATT_ADDRESS = 'companyAddress';
    CONST TABLE_COMPANY_ATT_COUNTRY = 'companyCountry';
    CONST TABLE_COMPANY_ATT_STATE = 'companyState';
    CONST TABLE_COMPANY_ATT_CITY = 'companyCity';
    CONST TABLE_COMPANY_ATT_ZIP = 'companyZip';
    CONST TABLE_COMPANY_ATT_EMAIL = 'companyEmail';
    CONST TABLE_COMPANY_ATT_CONTACT_NUMBER = 'companyContactNumber';
    CONST TABLE_COMPANY_ATT_CONTACT_PERSON_NAME = 'companyContactPerson';
    CONST TABLE_COMPANY_ATT_CONTACT_PERSON_NUMBER = 'companyContactPersonNumber';
    CONST TABLE_COMPANY_ATT_ADDED_TIME = 'addedTime';
    CONST TABLE_COMPANY_ATT_IS_DELETE = 'isDelete';

    /**
     * DEFINE COUNTRY TABLE
     */
    CONST TABLE_COUNTRY = 'tbl_country';
    CONST TABLE_COUNTRY_ATT_COUNTRY_ID = 'countryId';
    CONST TABLE_COUNTRY_ATT_COUNTRY_NAME = 'countryName';
    CONST TABLE_COUNTRY_ATT_CODE = 'code';
    CONST TABLE_COUNTRY_ATT_CODE_A3 = 'codeA3';
    CONST TABLE_COUNTRY_ATT_CODE_N3 = 'codeN3';
    CONST TABLE_COUNTRY_ATT_REGION = 'region';
    CONST TABLE_COUNTRY_STATUS = 'status';

    /**
     * DEFINE STATE TABLE
     */
    CONST TABLE_STATES = 'tbl_states';
    CONST TABLE_STATES_ATT_STATE_ID = 'stateId';
    CONST TABLE_STATES_ATT_STATE_NAME = 'stateName';
    CONST TABLE_STATES_ATT_STATE_SHORT_NAME = 'stateShortName';
    CONST TABLE_STATES_ATT_COUNTRY_ID = 'countryId';

    /**
     * DEFINE CITY TABLE
     */
    CONST TABLE_CITY = 'tbl_city';
    CONST TABLE_CITY_ATT_CITY_ID = 'cityId';
    CONST TABLE_CITY_ATT_CITY_NAME = 'cityName';
    CONST TABLE_CITY_ATT_STATE_SHORT_NAME = 'stateShortName';

    /**
     * DEFINE PROJECT TABLE
     */
    CONST TABLE_PROJECT = 'tbl_project';
    CONST TABLE_PROJECT_ATT_ID = 'id';
    CONST TABLE_PROJECT_ATT_COMPANY_ID = 'companyId';
    CONST TABLE_PROJECT_ATT_CLIENT_ID = 'clientId';
    CONST TABLE_PROJECT_ATT_PROJECT_TYPE_ID = 'projectTypeId';
    CONST TABLE_PROJECT_ATT_USER_ID = 'userId';
    CONST TABLE_PROJECT_ATT_PROJECT_NAME = 'projectName';
    CONST TABLE_PROJECT_ATT_PROJECT_EMAIL = 'projectEmail';
    CONST TABLE_PROJECT_ATT_PROJECT_DETAILS = 'projectDetails';
    CONST TABLE_PROJECT_ATT_PROJECT_COUNTRY = 'projectCountry';
    CONST TABLE_PROJECT_ATT_PROJECT_STATE = 'projectState';
    CONST TABLE_PROJECT_ATT_PROJECT_CITY = 'projectCity';
    CONST TABLE_PROJECT_ATT_ADDED_TIME = 'addedTime';
    CONST TABLE_PROJECT_ATT_IS_DELETE = 'isDelete';

    /**
     * DEFINE PROJECT TYPE TABLE
     */
    CONST TABLE_PROJECT_TYPE = 'tbl_project_type';
    CONST TABLE_PROJECT_TYPE_ATT_ID = 'id';
    CONST TABLE_PROJECT_TYPE_ATT_NAME = 'name';

    /**
     * DEFINE USER PRIVILEDGE TABLE
     */
    CONST TABLE_USER_PRIVILEDGE = 'tbl_user_priviledge';
    CONST TABLE_USER_PRIVILEDGE_ATT_ID = 'priviledgeId';
    CONST TABLE_USER_PRIVILEDGE_ATT_NAME = 'priviledgeName';

    /**
     * DEFINE CLIENT STATUS TABLE
     */
    CONST TABLE_CLIENT_STATUS = 'tbl_client_status';
    CONST TABLE_CLIENT_STATUS_ATT_ID = 'id';
    CONST TABLE_CLIENT_STATUS_ATT_CLIENT_ID = 'clientId';
    CONST TABLE_CLIENT_STATUS_ATT_USER_ID = 'userId';
    CONST TABLE_CLIENT_STATUS_ATT_MODIFICATION_TYPE = 'modificationType';
    CONST TABLE_CLIENT_STATUS_ATT_TIME = 'time';

    /**
     * DEFINE COMPANY STATUS TABLE
     */
    CONST TABLE_COMPANY_STATUS = 'tbl_company_status';
    CONST TABLE_COMPANY_STATUS_ATT_ID = 'id';
    CONST TABLE_COMPANY_STATUS_ATT_COMPANY_ID = 'companyId';
    CONST TABLE_COMPANY_STATUS_ATT_USER_ID = 'userId';
    CONST TABLE_COMPANY_STATUS_ATT_MODIFICATION_TYPE = 'modificationType';
    CONST TABLE_COMPANY_STATUS_ATT_TIME = 'time';

    /**
     * DEFINE PROJECT STATUS TABLE
     */
    CONST TABLE_PROJECT_STATUS = 'tbl_project_status';
    CONST TABLE_PROJECT_STATUS_ATT_ID = 'id';
    CONST TABLE_PROJECT_STATUS_ATT_PROJECT_ID = 'projectId';
    CONST TABLE_PROJECT_STATUS_ATT_USER_ID = 'userId';
    CONST TABLE_PROJECT_STATUS_ATT_MODIFICATION_TYPE = 'modificationType';
    CONST TABLE_PROJECT_STATUS_ATT_TIME = 'time';

    /**
     * DEFINE PROFILE STATUS TABLE
     */
    CONST TABLE_PROFILE_STATUS = 'tbl_profile_status';
    CONST TABLE_PROFILE_STATUS_ATT_ID = 'id';
    CONST TABLE_PROFILE_STATUS_ATT_PROFILE_ID = 'profileId';
    CONST TABLE_PROFILE_STATUS_ATT_USER_ID = 'userId';
    CONST TABLE_PROFILE_STATUS_ATT_MODIFICATION_TYPE = 'modificationType';
    CONST TABLE_PROFILE_STATUS_ATT_TIME = 'time';

    /**
     * DEFINE EMAIL STATUS TABLE
     */
    CONST TABLE_EMAIL_STATUS = 'tbl_email_status';
    CONST TABLE_EMAIL_STATUS_ATT_ID = 'id';
    CONST TABLE_EMAIL_STATUS_ATT_RECEIVE_ID = 'receiverId';
    CONST TABLE_EMAIL_STATUS_ATT_USER_ID = 'userId';
    CONST TABLE_EMAIL_STATUS_ATT_EMAIL_TYPE = 'emailType';
    CONST TABLE_EMAIL_STATUS_ATT_TIME = 'time';

    /**
     * DEFINE PLOT TABLE
     */
    CONST TABLE_PLOT = 'tbl_plot';
    CONST TABLE_PLOT_ATT_PLOT_ID = 'plotId';
    CONST TABLE_PLOT_ATT_PLOT_NAME = 'plotName';
    CONST TABLE_PLOT_ATT_PLOT_ADDESS = 'plotAddress';
    CONST TABLE_PLOT_ATT_PLOT_BLOCK = 'plotBlock';
    CONST TABLE_PLOT_ATT_PLOT_FACING = 'plotFacing';
    CONST TABLE_PLOT_ATT_PLOT_PROJECT_ID = 'plotProjectId';
    CONST TABLE_PLOT_ATT_PLOT_SELLER_ID = 'plotSellerId';
    CONST TABLE_PLOT_ATT_PLOT_BUYER_ID = 'plotBuyerId';
    CONST TABLE_PLOT_ATT_PLOT_STATUS = 'plotStatus';
    CONST TABLE_PLOT_ATT_PLOT_ASKING_PRICE = 'plotAskingPrice';
    CONST TABLE_PLOT_ATT_PLOT_ASKING_MIN_PRICE = 'plotAskingMinimumPrice';
    CONST TABLE_PLOT_ATT_PLOT_CURRENCY = 'plotCurrency';
    CONST TABLE_PLOT_ATT_PLOT_CONDITION = 'plotCondition';
    CONST TABLE_PLOT_ATT_PLOT_COMMENT = 'plotComment';
    CONST TABLE_PLOT_ATT_PLOT_IS_DELETE = 'isDelete';
    CONST TABLE_PLOT_ATT_PLOT_MARK_AS_COMPANY = 'markAsCompany';

    /**
     * DEFINE APARTMENT TABLE
     */
    CONST TABLE_APARTMENT = 'tbl_apartment';
    CONST TABLE_APARTMENT_ATT_APARTMENT_ID = 'apartmentId';
    CONST TABLE_APARTMENT_ATT_APARTMENT_PROJECT_ID = 'apartmentProjectId';
    CONST TABLE_APARTMENT_ATT_APARTMENT_NAME = 'apartmentName';
    CONST TABLE_APARTMENT_ATT_APARTMENT_ADDRESS = 'apartmentAddress';
    CONST TABLE_APARTMENT_ATT_APARTMENT_SIZE = 'apartmentSize';
    CONST TABLE_APARTMENT_ATT_APARTMENT_FLOOR = 'apartmentFloor';
    CONST TABLE_APARTMENT_ATT_APARTMENT_FACING = 'apartmentFacing';
    CONST TABLE_APARTMENT_ATT_APARTMENT_BED = 'apartmentBed';
    CONST TABLE_APARTMENT_ATT_APARTMENT_BATH = 'apartmentBath';
    CONST TABLE_APARTMENT_ATT_APARTMENT_ASKING_PRICE = 'apartmentAskingPrice';
    CONST TABLE_APARTMENT_ATT_APARTMENT_ASKING_MIN_PRICE = 'apartmentAskingMinimumPrice';
    CONST TABLE_APARTMENT_ATT_APARTMENT_CURRENCY = 'apartmentCurrency';
    CONST TABLE_APARTMENT_ATT_APARTMENT_SELLER_ID = 'apartmentSellerId';
    CONST TABLE_APARTMENT_ATT_APARTMENT_BUYER_ID = 'apartmentBuyerId';
    CONST TABLE_APARTMENT_ATT_APARTMENT_STATUS = 'apartmentStatus';
    CONST TABLE_APARTMENT_ATT_APARTMENT_CONDITION = 'apartmentCondition';
    CONST TABLE_APARTMENT_ATT_APARTMENT_COMMENT = 'apartmentComment';
    CONST TABLE_APARTMENT_ATT_APARTMENT_IS_DELETE = 'isDelete';
    CONST TABLE_APARTMENT_ATT_APARTMENT_MARK_AS_COMPANY = 'markAsCompany';

    /**
     * DEFINE PLOT BLOCK TABLE 
     */
    CONST TABLE_PLOT_BLOCK = 'tbl_plot_block';
    CONST TABLE_PLOT_BLOCK_ATT_BLOCK_ID = 'blockId';
    CONST TABLE_PLOT_BLOCK_ATT_BLOCK_NAME = 'blockName';

    /**
     * DEFINE PLOT CONDITION TABLE
     */
    CONST TABLE_PLOT_CONDITION = 'tbl_plot_condition';
    CONST TABLE_PLOT_CONDITION_ATT_CONDITION_ID = 'conditionId';
    CONST TABLE_PLOT_CONDITION_ATT_CONDITION_NAME = 'conditionName';

    /**
     * DEFINE PLOT FACING TABLE
     */
    CONST TABLE_PLOT_FACING = 'tbl_plot_facing';
    CONST TABLE_PLOT_FACING_ATT_FACE_ID = 'faceId';
    CONST TABLE_PLOT_FACING_ATT_FACE_NAME = 'faceName';

    /**
     * DEFINE PLOT STATUS TABLE
     */
    CONST TABLE_PLOT_STATUS = 'tbl_plot_status';
    CONST TABLE_PLOT_STATUS_ATT_STATUS_ID = 'statusId';
    CONST TABLE_PLOT_STATUS_ATT_STATUS_NAME = 'statusName';

    /**
     * DEFINE CURRENCY TABLE
     */
    CONST TABLE_CURRENCY = 'tbl_currency';
    CONST TABLE_CURRENCY_ATT_CURRENCY_ID = 'currencyId';
    CONST TABLE_CURRENCY_ATT_CURRENCY_NAME = 'currencyName';
    CONST TABLE_CURRENCY_ATT_CURRENCY_CODE = 'currencyCode';

    /**
     * DEFINE APARTMENT BATH TABLE
     */
    CONST TABLE_APARTMENT_BATH = 'tbl_apartment_bath';
    CONST TABLE_APARTMENT_BATH_ATT_BATH_ID = 'bathId';
    CONST TABLE_APARTMENT_BATH_ATT_BATH_VALUE = 'bathValue';

    /**
     * DEFINE APARTMENT BED TABLE
     */
    CONST TABLE_APARTMENT_BED = 'tbl_apartment_bed';
    CONST TABLE_APARTMENT_BED_ATT_BED_ID = 'bedId';
    CONST TABLE_APARTMENT_BED_ATT_BED_VALUE = 'bedValue';

    /**
     * DEFINE APARTMENT FACING TABLE
     */
    CONST TABLE_APARTMENT_FACING = 'tbl_apartment_facing';
    CONST TABLE_APARTMENT_FACING_ATT_FACE_ID = 'faceId';
    CONST TABLE_APARTMENT_FACING_ATT_FACE_NAME = 'faceName';

    /**
     * DEFINE APARTMENT FLOOR TABLE
     */
    CONST TABLE_APARTMENT_FLOOR = 'tbl_apartment_floor';
    CONST TABLE_APARTMENT_FLOOR_ATT_FLOOR_ID = 'floorId';
    CONST TABLE_APARTMENT_FLOOR_ATT_FLOOR_NAME = 'floorName';

    /**
     * DEFINE APARTMENT SIZE TABLE
     */
    CONST TABLE_APARTMENT_SIZE = 'tbl_apartment_size';
    CONST TABLE_APARTMENT_SIZE_ATT_SIZE_ID = 'sizeId';
    CONST TABLE_APARTMENT_SIZE_ATT_SIZE_VALUE = 'sizeValue';

    /**
     * DEFINE APARTMENT CONDITION TABLE
     */
    CONST TABLE_APARTMENT_CONDITION = 'tbl_apartment_condition';
    CONST TABLE_APARTMENT_CONDITION_ATT_CONDITION_ID = 'conditionId';
    CONST TABLE_APARTMENT_CONDITION_ATT_CONDITION_NAME = 'conditionName';

    /**
     * DEFINE APARTMENT STATUS TABLE
     */
    CONST TABLE_APARTMENT_STATUS = 'tbl_apartment_status';
    CONST TABLE_APARTMENT_STATUS_ATT_STATUS_ID = 'statusId';
    CONST TABLE_APARTMENT_STATUS_ATT_STATUS_NAME = 'statusName';

    /**
     * DEFINE LOG TABLE
     */
    CONST TABLE_LOG = 'tbl_log';
    CONST TABLE_LOG_ATT_ID = 'id';
    CONST TABLE_LOG_ATT_LOG_TXT = 'logTxt';
    CONST TABLE_LOG_ATT_TIME = 'time';

    /**
     * DEFINE COMMERCIAL TABLE
     */
    CONST TABLE_COMMERCIAL = 'tbl_commercial';
    CONST TABLE_COMMERCIAL_ATT_ID = 'id';
    CONST TABLE_COMMERCIAL_ATT_NAME = 'name';
    CONST TABLE_COMMERCIAL_ATT_ADDRESS = 'address';
    CONST TABLE_COMMERCIAL_ATT_FLOOR = 'floor';
    CONST TABLE_COMMERCIAL_ATT_SIZE = 'size';
    CONST TABLE_COMMERCIAL_ATT_ASKING_PRICE = 'askingPrice';
    CONST TABLE_COMMERCIAL_ATT_MINIMUM_ASKING_PRICE = 'minimumAskingPrice';
    CONST TABLE_COMMERCIAL_ATT_STATUS = 'status';
    CONST TABLE_COMMERCIAL_ATT_CONDITION = 'condition';
    CONST TABLE_COMMERCIAL_ATT_CURRENCY = 'currency';
    CONST TABLE_COMMERCIAL_ATT_PROJECT_ID = 'projectId';
    CONST TABLE_COMMERCIAL_ATT_SELLER_ID = 'sellerId';
    CONST TABLE_COMMERCIAL_ATT_BUYER_ID = 'buyerId';
    CONST TABLE_COMMERCIAL_ATT_IS_DELETE = 'isDelete';
    CONST TABLE_COMMERCIAL_ATT_MARK_AS_COMPANY = 'markAsCompany';
    CONST TABLE_COMMERCIAL_ATT_COMMENTS = 'comments';

    /**
     * DEFINE COMMERCIAL CONDITION TABLE
     */
    CONST TABLE_COMMERCIAL_CONDITION = 'tbl_commercial_condition';
    CONST TABLE_COMMERCIAL_CONDITION_ATT_ID = 'conditionId';
    CONST TABLE_COMMERCIAL_CONDITION_ATT_NAME = 'conditionName';

    /**
     * DEFINE COMMERCIAL FLOOR TABLE
     */
    CONST TABLE_COMMERCIAL_FLOOR = 'tbl_commercial_floor';
    CONST TABLE_COMMERCIAL_FLOOR_ATT_ID = 'id';
    CONST TABLE_COMMERCIAL_FLOOR_ATT_VALUE = 'value';

    /**
     * DEFINE COMMERCIAL SIZE TABLE
     */
    CONST TABLE_COMMERCIAL_SIZE = 'tbl_commercial_size';
    CONST TABLE_COMMERCIAL_SIZE_ATT_ID = 'id';
    CONST TABLE_COMMERCIAL_SIZE_ATT_VALUE = 'value';

    /**
     * DEFINE COMMERCIAL STATUS TABLE
     */
    CONST TABLE_COMMERCIAL_STATUS = 'tbl_commercial_status';
    CONST TABLE_COMMERCIAL_STATUS_ATT_STATUS_ID = 'statusId';
    CONST TABLE_COMMERCIAL_STATUS_ATT_STATUS_NAME = 'statusName';

    /**
     * DEFINE SOLD PLOT TABLE
     */
    CONST TABLE_SOLD_PLOT = 'tbl_sold_plot';
    CONST TABLE_SOLD_PLOT_ATT_ID = 'id';
    CONST TABLE_SOLD_PLOT_ATT_PLOT_ID = 'plotId';
    CONST TABLE_SOLD_PLOT_ATT_COMPANY_ID = 'companyId';
    CONST TABLE_SOLD_PLOT_ATT_CLIENT_ID = 'clientId';
    CONST TABLE_SOLD_PLOT_ATT_PROJECT_ID = 'projectId';
    CONST TABLE_SOLD_PLOT_ATT_SELLER_ID = 'sellerId';
    CONST TABLE_SOLD_PLOT_ATT_OLD_PROJECT_ID = 'oldProjectId';
    CONST TABLE_SOLD_PLOT_ATT_SUBTOTAL = 'subtotal';
    CONST TABLE_SOLD_PLOT_ATT_DOWN_PAYMENT = 'downPayment';
    CONST TABLE_SOLD_PLOT_ATT_INSTALLMENT_PERIOD = 'installmentPeriod';
    CONST TABLE_SOLD_PLOT_ATT_MONTH_PAYMENT = 'monthPayment';
    CONST TABLE_SOLD_PLOT_ATT_IS_INSTALLMENT_SALE = 'isInstallmentSale';
    CONST TABLE_SOLD_PLOT_ATT_COMMENT = 'comment';
    CONST TABLE_SOLD_PLOT_ATT_TIME = 'time';

    /**
     * DEFINE SOLD APARTMENT TABLE
     */
    CONST TABLE_SOLD_APARTMENT = 'tbl_sold_apartment';
    CONST TABLE_SOLD_APARTMENT_ATT_ID = 'id';
    CONST TABLE_SOLD_APARTMENT_ATT_APARTMENT_ID = 'apartmentId';
    CONST TABLE_SOLD_APARTMENT_ATT_COMPANY_ID = 'companyId';
    CONST TABLE_SOLD_APARTMENT_ATT_CLIENT_ID = 'clientId';
    CONST TABLE_SOLD_APARTMENT_ATT_PROJECT_ID = 'projectId';
    CONST TABLE_SOLD_APARTMENT_ATT_SELLER_ID = 'sellerId';
    CONST TABLE_SOLD_APARTMENT_ATT_OLD_PROJECT_ID = 'oldProjectId';
    CONST TABLE_SOLD_APARTMENT_ATT_SUBTOTAL = 'subtotal';
    CONST TABLE_SOLD_APARTMENT_ATT_DOWN_PAYMENT = 'downPayment';
    CONST TABLE_SOLD_APARTMENT_ATT_INSTALLMENT_PERIOD = 'installmentPeriod';
    CONST TABLE_SOLD_APARTMENT_ATT_MONTH_PAYMENT = 'monthPayment';
    CONST TABLE_SOLD_APARTMENT_ATT_IS_INSTALLMENT_SALE = 'isInstallmentSale';
    CONST TABLE_SOLD_APARTMENT_ATT_COMMENT = 'comment';
    CONST TABLE_SOLD_APARTMENT_ATT_TIME = 'time';

    /**
     * DEFINE SOLD COMMERCIAL TABLE
     */
    CONST TABLE_SOLD_COMMERCIAL = 'tbl_sold_commercial';
    CONST TABLE_SOLD_COMMERCIAL_ATT_ID = 'id';
    CONST TABLE_SOLD_COMMERCIAL_ATT_COMMERCIAL_ID = 'commercialId';
    CONST TABLE_SOLD_COMMERCIAL_ATT_COMPANY_ID = 'companyId';
    CONST TABLE_SOLD_COMMERCIAL_ATT_CLIENT_ID = 'clientId';
    CONST TABLE_SOLD_COMMERCIAL_ATT_PROJECT_ID = 'projectId';
    CONST TABLE_SOLD_COMMERCIAL_ATT_SELLER_ID = 'sellerId';
    CONST TABLE_SOLD_COMMERCIAL_ATT_OLD_PROJECT_ID = 'oldProjectId';
    CONST TABLE_SOLD_COMMERCIAL_ATT_SUBTOTAL = 'subtotal';
    CONST TABLE_SOLD_COMMERCIAL_ATT_DOWN_PAYMENT = 'downPayment';
    CONST TABLE_SOLD_COMMERCIAL_ATT_INSTALLMENT_PERIOD = 'installmentPeriod';
    CONST TABLE_SOLD_COMMERCIAL_ATT_MONTH_PAYMENT = 'monthPayment';
    CONST TABLE_SOLD_COMMERCIAL_ATT_IS_INSTALLMENT_SALE = 'isInstallmentSale';
    CONST TABLE_SOLD_COMMERCIAL_ATT_COMMENT = 'comment';
    CONST TABLE_SOLD_COMMERCIAL_ATT_TIME = 'time';

}
