<?php

class siteConfig {

    //define view site master
    CONST SITE_MASTER = "siteMaster";
    //define controllers
    CONST CONTROLLER_USER = 'user';
    CONST CONTROLLER_CLIENT = 'client';
    CONST CONTROLLER_COMPANY = 'company';
    CONST CONTROLLER_PROJECT = 'project';
    CONST CONTROLLER_PLOT = 'plot';
    CONST CONTROLLER_APARTMENT = 'apartment';
    CONST CONTROLLER_COMMERCIAL = 'commercial';
    CONST CONTROLLER_PAYMENT = 'payment';
    //define view modules
    CONST MOD_HEADER = 'mod/modHeader';
    CONST MOD_FOOTER = 'mod/modFooter';
    CONST MOD_MENU = 'mod/modMenu';
    //define view component
    CONST COMPONENT_USER = 'comp/user/compUserLogin';
    CONST COMPONENT_USER_DASHBOARD = 'comp/user/compUserDashboard';
    CONST COMPONENT_USER_PROFILE = 'comp/user/compUserProfile';
    CONST COMPONENT_USER_EDIT_PROFILE = 'comp/user/compUserEditProfile';
    CONST COMPONENT_USER_CHANGE_PASSWORD = 'comp/user/compChangePassword';
    CONST COMPONENT_USER_LIST = 'comp/user/compUserList';
    CONST COMPONENT_USER_DETAILS = 'comp/user/compUserDetails';
    CONST COMPONENT_USER_ADD = 'comp/user/compUserAdd';
    CONST COMPONENT_USER_PROFILE_EDIT = 'comp/user/compUserProfileEdit';
    CONST COMPONENT_ADD_CLIENT = 'comp/client/compAddClient';
    CONST COMPONENT_CLIENT_LIST = 'comp/client/compClientList';
    CONST COMPONENT_CLIENT_DETAILS = 'comp/client/compClientDetails';
    CONST COMPONENT_CLIENT_EDIT = 'comp/client/compClientEdit';
    CONST COMPONENT_ADD_COMPANY = 'comp/company/compAddCompany';
    CONST COMPONENT_COMPANY_LIST = 'comp/company/compCompanyList';
    CONST COMPONENT_COMPANY_DETAILS = 'comp/company/compCompanyDetails';
    CONST COMPONENT_COMPANY_EDIT = 'comp/company/compCompanyEdit';
    CONST COMPONENT_COMPANY_ADD_FORM = 'comp/company/compCompanyAddForm';
    CONST COMPONENT_ADD_PROJECT = 'comp/project/compAddProject';
    CONST COMPONENT_PROJECT_LIST = 'comp/project/compProjectList';
    CONST COMPONENT_PROJECT_DETAILS = 'comp/project/compProjectDetails';
    CONST COMPONENT_PROJECT_EDIT = 'comp/project/compProjectEdit';
    CONST COMPONENT_PROJECT_MANAGE_TYPE = 'comp/project/compProjectManageType';
    CONST COMPONENT_ADD_PLOT = 'comp/plot/compAddPlot';
    CONST COMPONENT_ADD_PLOT_STEP2 = 'comp/plot/compAddPlotStep2';
    CONST COMPONENT_ADD_PLOT_STEP3 = 'comp/plot/compAddPlotStep3';
    CONST COMPONENT_ADD_PLOT_STEP4 = 'comp/plot/compAddPlotStep4';
    CONST COMPONENT_PLOT_LIST = 'comp/plot/compPlotList';
    CONST COMPONENT_PLOT_DETAILS = 'comp/plot/compPlotDetails';
    CONST COMPONENT_PLOT_EDIT = 'comp/plot/compPlotEdit';
    CONST COMPONENT_PLOT_SELL = 'comp/plot/compPlotSell';
    CONST COMPONENT_ADD_APARTMENT = 'comp/apartment/compAddApartment';
    CONST COMPONENT_ADD_APARTMENT_STEP2 = 'comp/apartment/compAddApartmentStep2';
    CONST COMPONENT_ADD_APARTMENT_STEP3 = 'comp/apartment/compAddApartmentStep3';
    CONST COMPONENT_ADD_APARTMENT_STEP4 = 'comp/apartment/compAddApartmentStep4';
    CONST COMPONENT_APARTMENT_LIST = 'comp/apartment/compApartmentList';
    CONST COMPONENT_APARTMENT_DETAILS = 'comp/apartment/compApartmentDetails';
    CONST COMPONENT_APARTMENT_EDIT = 'comp/apartment/compApartmentEdit';
    CONST COMPONENT_ADD_COMMERCIAL = 'comp/commercial/compAddCommercial';
    CONST COMPONENT_ADD_COMMERCIAL_STEP2 = 'comp/commercial/compAddCommercialStep2';
    CONST COMPONENT_ADD_COMMERCIAL_STEP3 = 'comp/commercial/compAddCommercialStep3';
    CONST COMPONENT_ADD_COMMERCIAL_STEP4 = 'comp/commercial/compAddCommercialStep4';
    CONST COMPONENT_COMMERCIAL_LIST = 'comp/commercial/compCommercialList';
    CONST COMPONENT_COMMERCIAL_DETAILS = 'comp/commercial/compCommercialDetails';
    CONST COMPONENT_COMMERCIAL_EDIT = 'comp/commercial/compCommercialEdit';
    CONST COMPONENT_APARTMENT_SELL = 'comp/apartment/compApartmentSell';
    CONST COMPONENT_COMMERCIAL_SELL = 'comp/commercial/compCommercialSell';
    CONST COMPONENT_DUE_PAYMENT = 'comp/payment/compDuePayment';
    //define method user controller
    CONST METHOD_USER_INDEX = '/index/';
    CONST METHOD_USER_DASHBOARD = '/dashboard/';
    CONST METHOD_USER_LOGOUT = '/logout/';
    CONST METHOD_USER_PROFILE = '/profile/';
    CONST METHOD_USER_EDIT_PROFILE = '/editProfile/';
    CONST METHOD_USER_CHANGE_PASSWORD = '/changePassword/';
    CONST METHOD_USER_LIST = '/userList/';
    CONST METHOD_USER_ADD = '/addUser/';
    CONST METHOD_VIEW_PROFILE = '/viewProfile/';
    CONST METHOD_USER_PROFILE_EDIT = '/profileEdit/';
    //define method client controller
    CONST METHOD_ADD_CLIENT = '/addClient/';
    CONST METHOD_VIEW_CLIENT = '/viewClient/';
    CONST METHOD_CLIENT_LIST = '/clientList/';
    CONST METHOD_ALL_CLIENT = '/allClient/';
    CONST METHOD_CLIENT_EDIT = '/editClient/';
    CONST METHOD_DELETE_CLIENT = '/deleteClient/';
    //define method company controller
    CONST METHOD_ADD_COMPANY = '/addCompany/';
    CONST METHOD_COMPANY_LIST = '/companyList/';
    CONST METHOD_ALL_COMPANY = '/allCompany/';
    CONST METHOD_VIEW_COMPANY = '/viewCompany/';
    CONST METHOD_COMPANY_EDIT = '/editCompany/';
    CONST METHOD_DELETE_COMPANY = '/deleteCompany/';
    //define method project controller
    CONST METHOD_ADD_PROJECT = '/addProject/';
    CONST METHOD_PROJECT_LIST = '/projectList/';
    CONST METHOD_ALL_PROJECT = '/allProject/';
    CONST METHOD_VIEW_PROJECT = '/viewProject/';
    CONST METHOD_PROJECT_EDIT = '/editProject/';
    CONST METHOD_DELETE_PROJECT = '/deleteProject/';
    CONST METHOD_PROJECT_MANAGE_TYPE = '/manageType/';
    //define method plot controller
    CONST METHOD_PLOT_ADD_PLOT = '/addPlot/';
    CONST METHOD_PLOT_LIST_PLOT = '/plotList/';
    CONST METHOD_PLOT_ALL_PLOT = '/allPlot/';
    CONST METHOD_PLOT_VIEW_PLOT = '/viewPlot/';
    CONST METHOD_PLOT_EDIT_PLOT = '/editPlot/';
    CONST METHOD_PLOT_DELETE_PLOT = '/deletePlot/';
    CONST METHOD_PLOT_SELL_PLOT = '/sellPlot/';
    //define method apartment controller
    CONST METHOD_APARTMENT_ADD_APARTMENT = '/addApartment/';
    CONST METHOD_APARTMENT_LIST_APARTMENT = '/apartmentList/';
    CONST METHOD_APARTMENT_ALL_APARTMENT = '/allApartment/';
    CONST METHOD_APARTMENT_VIEW_APARTMENT = '/viewApartment/';
    CONST METHOD_APARTMENT_EDIT_APARTMENT = '/editApartment/';
    CONST METHOD_APARTMENT_DELETE_APARTMENT = '/deleteApartment/';
    CONST METHOD_APARTMENT_SELL_APARTMENT = '/sellApartment/';
    //define method commercial controller
    CONST METHOD_COMMMERCIAL_ADD_COMMMERCIAL = '/addCommercial/';
    CONST METHOD_COMMMERCIAL_LIST_COMMMERCIAL = '/commercialList/';
    CONST METHOD_COMMMERCIAL_ALL_COMMMERCIAL = '/allCommercial/';
    CONST METHOD_COMMMERCIAL_VIEW_COMMMERCIAL = '/viewCommercial/';
    CONST METHOD_COMMMERCIAL_EDIT_COMMMERCIAL = '/editCommercial/';
    CONST METHOD_COMMMERCIAL_DELETE_COMMMERCIAL = '/deleteCommercial/';
    CONST METHOD_COMMMERCIAL_SELL_COMMMERCIAL = '/sellCommercial/';
    //define method payment controller
    CONST METHOD_ALL_PAYMENT = '/allPayment/';
    CONST METHOD_ADD_PAYMENT = '/addPayment/';
    CONST METHOD_DUE_PAYMENT = '/duePayment/';
    CONST METHOD_PAID_PAYMENT = '/paidPayment';

}
